apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mohanvamsikrishna/my-mongo:v1   
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db   
      volumes:
      - name: mongo-storage
        hostPath:
          path: /mnt/data/mongo   #On the node, this directory will hold the data (DirectoryOrCreate ensures it is created if not present)
          type: DirectoryOrCreate

